org: moulout
app: sls-framework-2-lambda
service: sls-framework-2-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  simulandoUploadCsv:
    handler: cadastro_batch/local/index.simulandoUploadCsv
    events:
      - httpApi:
          path: /alunos/batch
          method: post
  cadastrarAlunos:
    handler: cadastro_batch/local/index.cadastrarAlunos
    events:
      - s3:
          bucket: alunos-csv-local
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv

plugins:
  - serverless-offline
  - serverless-s3-local
